objects/Forward_Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_Currency__c</fullName>
        <label>Custom Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Rate</label>
        <referenceTo>Market_Rate__c</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Settlement_Amount__c</fullName>
        <label>Settlement Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Number__c</fullName>
        <label>Transaction Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Forward Contracts</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Forward Contracts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Historical_Payments__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Historical Payments</relationshipLabel>
        <relationshipName>Historical_Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>YYYYMM</description>
        <label>Date</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Historical Payments</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Historical Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Holding_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Holding Balances</relationshipLabel>
        <relationshipName>Holding_Balances</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Market_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Rate</label>
        <referenceTo>Market_Rate__c</referenceTo>
        <relationshipLabel>Holding Balances</relationshipLabel>
        <relationshipName>Holding_Balances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Holding Balance</label>
    <nameField>
        <displayFormat>HB-{0000}</displayFormat>
        <label>Holding Balance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holding Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Input__c.object
<CustomObject>
    <fields>
        <fullName>Input_Type__c</fullName>
        <description>This is the selection list used on the page to create a new input record</description>
        <label>Input Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Inflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - WUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Outflow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Invoice Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <formula>TEXT(CurrencyIsoCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Settlement_Amount__c</fullName>
        <description>This will be used only in field set. No use on UI</description>
        <inlineHelpText>This will be used only in field set. No use on UI</inlineHelpText>
        <label>Amount in Settlement Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Last_Updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

classes/test_Utility.cls
/**=====================================================================
 * Name: test_Utility 
 * Description: utility class for for test data creation
 * Created Date: Mar 13, 2015
 * Created By: Aashita Sharma 
 =====================================================================*/

public with sharing class test_Utility {
            
   // method to create invoice record
    public static Invoice__c createInvoice(boolean isInsert){       
        Invoice__c invoice = new Invoice__c();
        invoice.CurrencyIsoCode = 'USD';
        if(isInsert)
        insert invoice;
        return invoice;
    }
    
    
    public static Input__c createInputWithType(boolean isInsert, String inputType, String accId){
      Input__c input = new Input__c(Input_Type__c = inputType);
      input.Amount__c = 11;
      input.Parent_Account__c = accId;
      input.CurrencyIsoCode = 'INR';
      input.Custom_Currency__c = 'INR';
      input.Transaction_Date__c = date.today().addDays(2);
      
      if(isInsert) 
      insert input;
      return input;
    }
    
    public static Input__c createInput(boolean isInsert){
      Input__c input = new Input__c(Input_Type__c = 'Purchase Order');
      input.Amount__c = 11;
      input.CurrencyIsoCode = 'INR';
      input.Custom_Currency__c = 'INR';
      input.Transaction_Date__c = date.today().addDays(2);
      
      if(isInsert) 
      insert input;
      return input;
    }
	public static Attachment addAttachmentToParent(Id parentId, String attName, String testData) {  
	    Blob b = Blob.valueOf(testData);  
	      
	    Attachment attachment = new Attachment();  
	    attachment.ParentId = parentId;  
	    attachment.Name = attName;  
	    attachment.Body = b;  
	      
	    insert(attachment);  
	    return attachment;
	}  
    public static User createTestUser(boolean isInsert){
       Campaign camp = new Campaign(Name= 'Bronze Trigger Emails');
        insert camp; 
      
      Account acc = new Account();
      acc.Name = 'testname';
      insert acc;
      
      Contact contact = new Contact();
      contact.AccountId =  acc.Id;
      contact.LastName = 'testlastname';
      insert contact;
      
      User testUser = new User();
      //testUser = new User();
      testUser.alias = 'testuser';
      testUser.Email = 'testuser@test123.com';
      testUser.EmailEncodingKey = 'ISO-8859-1';
      testUser.LanguageLocaleKey = 'en_US';
      testUser.LastName = 'Test User567';
      testUser.LocaleSidKey = 'en_AU';
      testUser.Account_Administrator__c = false;
      testUser.ProfileId = [SELECT Id FROM Profile WHERE Name LIKE 'Partner community - FX management tool' LIMIT 1].Id;
      testUser.TimeZoneSidKey = 'Australia/Sydney';
      testUser.UserName = 'testuser@travelex.com.au';
      testUser.ContactId = contact.Id;
      testUser.DefaultCurrencyIsoCode = 'INR';
      if(isInsert)
      insert testUser;
      return testUser;
    }   
    
    
    public static Historical_Payments__c createHistoricalPayments(ID accID ,Boolean isInsert) {
    	Historical_Payments__c payment = new Historical_Payments__c(Account_ID__c = accID, Amount__c = 14, Date__c = '201411', CurrencyISOCode = 'INR');
    	if(isInsert) {
    		insert payment;
    	} 
    	return payment;
    }
    
    public static Holding_Balance__c createHoldingBalance(ID accID ,Boolean isInsert) {
    	Market_Rate__c mRate = new Market_Rate__c(Currency_Code__c = 'INR', Currency_Name__c = 'INR', Currency_Value__c = 60, Last_Updated__c = System.today());
    	insert mRate;
    	Holding_Balance__c holdingBal = new Holding_Balance__c(Account__c = accID, Amount__c = 10000, Custom_Currency__c = 'INR', External_id__c = (datetime.now()+''));
    	holdingBal.Market_Rate__c = mRate.id;
    	if(isInsert) {
    		insert holdingBal;
    	} 
    	return holdingBal;
    } 
    
    public static Account createAccount(Boolean isInsert) {
      Account acc = new Account();
      acc.Name = 'testname';
      if(isInsert) {
      	insert acc;
      } 
      return acc;
    }   
    
    public static Beneficiary__c createBeneficiary(String name, ID accID, Boolean isInsert) {
    	Bene_Enrollment_Campaign__c beneEnrollment = new Bene_Enrollment_Campaign__c(Account__c = accID, Campaign_Start_Date__c = System.today(), Campaign_End_Date__c = System.today().addDays(30), Campaign_Status__c = 'Planned');
    	insert beneEnrollment;
    	Beneficiary__c beneficiary = new Beneficiary__c(Name = name, Account_Name__c = accID, Enrollment_Campaign__c = beneEnrollment.id);
    	if(isInsert) {
    		insert beneficiary;
    	}
    	return beneficiary;
    }
    
    public static Forward_Contracts__c createForwardContracts(ID accID, Boolean isInsert) {
         Forward_Contracts__c forwardContracts = new  Forward_Contracts__c();
         forwardContracts.Account_ID__c = accID;

         forwardContracts.Settlement_Amount__c = 20; 
         forwardContracts.Maturity_Date__c =  Date.today().addDays(5);
         forwardContracts.Start_Date__c = Date.today();
         forwardContracts.Transaction_Number__c = 25;
         forwardContracts.Custom_Currency__c = 'USD';
         if(isInsert) {
         	insert forwardContracts;
         } 
         return forwardContracts;    
    }          
     
     
    public static User createCommUser(Id conId, Boolean isInsert){
    	User testUser = new User();
      	testUser.alias = 'testuder';
      	testUser.Email = 'testuser@test1233.com';
      	testUser.EmailEncodingKey = 'ISO-8859-1';
      	testUser.LanguageLocaleKey = 'en_US';
      	testUser.LastName = 'Test User5627';
      	testUser.LocaleSidKey = 'fr';
      	testUser.Account_Administrator__c = false;
      	testUser.ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%CCT%' LIMIT 1].Id;
      	testUser.TimeZoneSidKey = 'Australia/Sydney';
      	testUser.UserName = 'testuser@travelex.com.auc';
      	testUser.ContactId = conId;
      	testUser.DefaultCurrencyIsoCode = 'INR';
      	if(isInsert)
      		insert testUser;
      	return testUser;
	}
}