objects/Forward_Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Market_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Rate</label>
        <referenceTo>Market_Rate__c</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Settlement_Amount__c</fullName>
        <label>Settlement Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Number__c</fullName>
        <label>Transaction Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Forward Contracts</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Forward Contracts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Historical_Payments__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Historical Payments</relationshipLabel>
        <relationshipName>Historical_Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>YYYYMM</description>
        <label>Date</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketRate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Rate</label>
        <referenceTo>Market_Rate__c</referenceTo>
        <relationshipLabel>Historical Payments</relationshipLabel>
        <relationshipName>Historical_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Historical Payments</label>
    <nameField>
        <displayFormat>HP-{0000}</displayFormat>
        <label>Historical Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Holding_Balance__c.object
<CustomObject>
    <fields>
        <fullName>Market_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Rate</label>
        <referenceTo>Market_Rate__c</referenceTo>
        <relationshipLabel>Holding Balances</relationshipLabel>
        <relationshipName>Holding_Balances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Holding Balance</label>
    <nameField>
        <displayFormat>HB-{0000}</displayFormat>
        <label>Holding Balance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holding Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Last_Updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

classes/AccountHoldingPieChartCtlTest.cls
/**=====================================================================
 * Name		    : AccountHoldingPieChartCtlTest
 * Description  : Apex unit test for AccountHoldingPieChartCtl.cls
 * Created Date : 24th March 2015
 * Created By   : Shailendra Singh (JDC)
 * Date Modified                Modified By                  Description of the update
 =====================================================================*/
@isTest
private class AccountHoldingPieChartCtlTest { 

    static testMethod void myUnitTest() {
        User portalUser = test_Utility.createTestUser(true);
        System.runAs(portalUser){
        	createTestData();
	        AccountHoldingPieChartCtl ctrl = new AccountHoldingPieChartCtl();   
	        ctrl.getPieData();
	        
	        List<AccountHoldingPieChartCtl.PieWedgeData> result = ctrl.getBarChartData();
	        
	        System.assertEquals(result.size(), 1);
	        
	        ctrl.getPieData1();    
	        
	        System.debug('ctrl.ForwardBalanceColor =>' + ctrl.ForwardBalanceColor);
	        System.debug('ctrl.isNonCCTuser =>' + ctrl.isNonCCTuser);
	        
	   }
   }
   
   private static void createTestData() {
        List<Historical_Payments__c> hPayments = new List<Historical_Payments__c>();
    	User userLoggedIn = [Select Name,contactId, contact.AccountId FROM User WHERE id =: UserInfo.getUserId()];
   		ID accId = userLoggedIn.Contact.AccountId;
		Market_Rate__c mRate = new Market_Rate__c(Currency_Code__c = 'CAD', Currency_Name__c = 'Canadian Doller', Currency_Value__c = 1.68, Last_Updated__c = System.today());
		insert mRate;     	   		
   		        
        hPayments.add(test_Utility.createHistoricalPayments(accId, false));
        hPayments.add(test_Utility.createHistoricalPayments(accId, false));
        hPayments.add(test_Utility.createHistoricalPayments(accId, false));
        hPayments.get(2).Date__c = System.today().year() + '' + System.today().month();
        
        hPayments.get(0).MarketRate__c = mRate.id;
        hPayments.get(1).MarketRate__c = mRate.id;
        hPayments.get(2).MarketRate__c = mRate.id;
        
        
        insert hPayments;
        
        Holding_Balance__c hb = test_Utility.createHoldingBalance(accID, true);
        
    	
    	Forward_Contracts__c forwardContracts = new  Forward_Contracts__c();
        forwardContracts.Account_ID__c = accId;
        forwardContracts.Settlement_Amount__c = 20; 
        forwardContracts.Maturity_Date__c =  Date.today().addDays(5);
        forwardContracts.Start_Date__c = Date.today();
        forwardContracts.Transaction_Number__c = 25;
        insert forwardContracts;     	   	
   }   
}