objects/Forward_Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FX_Balance__c</fullName>
        <label>FX Balance</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Forward Contracts</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Forward Contracts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Input__c.object
<CustomObject>
    <fields>
        <fullName>Input_Type__c</fullName>
        <description>This is the selection list used on the page to create a new input record</description>
        <label>Input Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Inflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - WUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Outflow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CashFlowComponentCloneTest.cls
/**
 * Appirio, Inc
 * Name             : CashFlowComponentCloneTest
 * Created Date     : 26 March 2015 
 * Description      : Test class for CashFlowComponentClone
 */
@isTest
private class CashFlowComponentCloneTest {
	static User portalUser;
	
    static testMethod void myUnitTest() {
    	portalUser = test_Utility.createTestUser(true);
    	System.runAs(portalUser) {
    		createTestData();
    		
    		Test.startTest();
    		
        	CashFlowComponentClone ctrl = new CashFlowComponentClone();
        	CashFlowComponentClone.selMonth = 3;
        	ctrl.cur = 'INR';
        	System.debug('ctrl.isNonCCTuser =>' + ctrl.isNonCCTuser);
        	ctrl.getMonths();
        	ctrl.getSpacer();
        	ctrl.firstMonthToDisplay(portalUser.ContactId, portalUser.Contact.AccountId);
        	ctrl.monthSearch(System.today());
        	
        	
        	
        	ctrl = new CashFlowComponentClone();
        	ctrl.cur = 'Total';
        	CashFlowComponentClone.selMonth = 3;
        	System.debug('ctrl.isNonCCTuser =>' + ctrl.isNonCCTuser);
        	ctrl.getMonths();
        	ctrl.getSpacer();
        	ctrl.firstMonthToDisplay(portalUser.ContactId, portalUser.Contact.AccountId);
        	ctrl.monthSearch(System.today());        
        	ctrl.getUserCurrency();	
        	
        	Test.stopTest();
        	
        	System.assert(ctrl.outflowTotal.size() != 0);
    	}
    	User currentUser = [Select   Id, ContactId, DefaultCurrencyIsoCode, Name, Contact.AccountId, IsPrmSuperUser, CurrencyIsoCode FROM  User WHERE  Id =: UserInfo.getUserId() LIMIT 1];
    	CashFlowComponentClone ctrl = new CashFlowComponentClone();
    	CashFlowComponentClone.selMonth = 3;
    	ctrl.cur = 'INR';
    	ctrl.getMonths();
    	ctrl.getSpacer();
    	ctrl.firstMonthToDisplay(currentUser.ContactId, currentUser.Contact.AccountId);
    	ctrl.monthSearch(System.today());
        	    	
    	ctrl = new CashFlowComponentClone();
    	ctrl.cur = 'Total';
    	CashFlowComponentClone.selMonth = 3;
    	ctrl.getMonths();
    	ctrl.getSpacer();
    	ctrl.firstMonthToDisplay(currentUser.ContactId, currentUser.Contact.AccountId);
    	ctrl.monthSearch(System.today());      
    	
    	List<Input__c> inputList = new List<Input__c>();
    	Forward_Contracts__c frwd = new Forward_Contracts__c();
    	frwd.FX_Balance__c = 28334;
    	frwd.Maturity_Date__c = system.today();
    	frwd.Account_ID__c = portalUser.Contact.AccountId;
    	insert frwd;
    	inputList.add(test_Utility.createInput(false));    	
    	ctrl.addToTradingReceipts(inputList.get(0));
    	ctrl.addToInflowOther(inputList.get(0));
    	ctrl.addToPurchaseOrder(inputList.get(0));
    	ctrl.addToForecastOrder(inputList.get(0));
    	ctrl.addToOutflowOther(inputList.get(0));
    	ctrl.addToForwardWUBS(frwd);
    	ctrl.addToForwardOther(inputList.get(0));
    	
    	ctrl.addToOptionsWUBSProtection(inputList.get(0));
    	ctrl.addToOptionsWUBSObligation(inputList.get(0));
    	ctrl.addToOptionsOtherProtection(inputList.get(0));
    	ctrl.addToOptionsOtherObligation(inputList.get(0));
    }
    
    static void createTestData() {
    	portalUser = [Select   Id, ContactId, DefaultCurrencyIsoCode, Name, Contact.AccountId, IsPrmSuperUser, CurrencyIsoCode FROM  User WHERE  Id =: UserInfo.getUserId() LIMIT 1];
    	List<Input__c> inputList = new List<Input__c>();
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	inputList.add(test_Utility.createInput(false));
    	
    	inputList.get(1).Input_Type__c = 'Forecast Outgoing';
    	inputList.get(2).Input_Type__c = 'Forecast Outflow';
    	inputList.get(3).Input_Type__c = 'Option - Other';
    	inputList.get(4).Input_Type__c = 'Forecast Inflow';
    	
    	
    	insert inputList;
    	
    	Invoice__c invoice = test_Utility.createInvoice(true);
    	
    	
    	
    	
    	test_Utility.createHoldingBalance(portalUser.Contact.AccountId, true);
    	test_Utility.createForwardContracts(portalUser.Contact.AccountId, true);
    }
}