objects/Forward_Contracts__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Converted_Amount__c</fullName>
        <formula>FX_Balance__c  /   Base_USD__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Converted Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Custom_Currency__c</fullName>
        <label>Custom Currency</label>
        <picklist>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AOK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ATS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BEF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FX_Amount__c</fullName>
        <label>FX Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FX_Balance__c</fullName>
        <label>FX Balance</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FX_Currency__c</fullName>
        <label>FX Currency</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Rate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market Rate</label>
        <referenceTo>Market_Rate__c</referenceTo>
        <relationshipLabel>Forward Contracts</relationshipLabel>
        <relationshipName>Forward_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Settlement_Amount__c</fullName>
        <label>Settlement Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Settlement_Balance__c</fullName>
        <label>Settlement Balance</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Number__c</fullName>
        <label>Transaction Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Forward Contracts</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Forward Contracts Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forward Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Market_Rate__c.object
<CustomObject>
</CustomObject>

classes/ForwardContractTriggerHandler.cls
/**=====================================================================
 * Name: ForwardContractTriggerHandler
 * Description: Related to ForwardContractTrigger
 * Created Date: Feb 09, 2015
 * Created By: Nishant Bansal (JDC)
 * 
 * Date Modified                Modified By                  Description of the update
 	March/17/2015				Ranjeet Singh					I-150167	: Currency Feed not being uploaded to SFDC
 =====================================================================*/
 
public with sharing class ForwardContractTriggerHandler {
	
	// Before Insert of Forward Contracts Record
	public static void beforeInsert(list<Forward_Contracts__c> forwardContractList){ 
		updateMarketRate(forwardContractList,null);
	}
	
	// Before Update of Forward Contracts Record
	public static void beforeUpdate(list<Forward_Contracts__c> forwardContractList, Map<Id,Forward_Contracts__c> oldMap){
		updateMarketRate(forwardContractList,oldMap);
	}
	
	// Update the Market Rate in Forward Contracts 
	public static void updateMarketRate(list<Forward_Contracts__c> forwardContractList, Map<Id,Forward_Contracts__c> oldMap){
		//I-150167	: Currency Feed not being uploaded to SFDC
		// set of currency ISO codes associated with forward contacts passed in
		Set<String> currencyIsoCodes = new Set<String>();
		for(Forward_Contracts__c newfc : forwardContractList ) {
			if(oldMap == null || newfc.Custom_Currency__c != oldMap.get(newfc.id).Custom_Currency__c /*|| newfc.FX_Amount__c != oldMap.get(newfc.id).FX_Amount__c
				|| newfc.Account_ID__c != oldMap.get(newfc.id).Account_ID__c || newfc.Converted_Amount__c != oldMap.get(newfc.id).Converted_Amount__c
				|| newfc.FX_Balance__c != oldMap.get(newfc.id).FX_Balance__c || newfc.FX_Currency__c != oldMap.get(newfc.id).FX_Currency__c
				|| newfc.Maturity_Date__c != oldMap.get(newfc.id).Maturity_Date__c || newfc.Maturity_Date__c != oldMap.get(newfc.id).Maturity_Date__c
				|| newfc.Settlement_Amount__c != oldMap.get(newfc.id).Settlement_Amount__c || newfc.Settlement_Amount__c != oldMap.get(newfc.id).Settlement_Amount__c
				|| newfc.Settlement_Balance__c != oldMap.get(newfc.id).Settlement_Balance__c || newfc.Start_Date__c != oldMap.get(newfc.id).Start_Date__c
				|| newfc.Transaction_Number__c != oldMap.get(newfc.id).Transaction_Number__c*/) {
				currencyIsoCodes.add(newfc.Custom_Currency__c);
			}
		}	
		
		// Market rate associated with above added currency ISO codes
		Map<String, Market_Rate__c>	marketRateMap = new Map<String, Market_Rate__c>();
    	for(Market_Rate__c marketRate : [Select Id, Currency_Code__c FROM Market_Rate__c WHERE Currency_Code__c IN : currencyIsoCodes]) {
			marketRateMap.put(marketRate.Currency_Code__c, marketRate);
    	}

		for(Forward_Contracts__c newfc : forwardContractList ) {
			if(marketRateMap.containsKey(newfc.Custom_Currency__c)) {
				newfc.Market_Rate__c = marketRateMap.get(newfc.Custom_Currency__c).Id;
			}
		}    	
    	
	}
	
}