objects/Input_Beneficiary__c.object
<CustomObject>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Invoice Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date_Span__c</fullName>
        <formula>ABS(Today()-  Due_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Date Span</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Input_Beneficiary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beneficiary</label>
        <referenceTo>Input_Beneficiary__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval (Open)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TopPendingInvoicesCtrl.cls
/**=====================================================================
 * Name: TopPendingInvoicesCtrl
 * Description: Related to TopPendingInvoices Page
 * Created Date: Jan 15, 2015
 * Created By: Nishant Bansal (JDC)
 * 
 * Date Modified                Modified By                  Description of the update
 =====================================================================*/
public without sharing class TopPendingInvoicesCtrl {
	
    public Id accId {get;set;}
    public List<InvoiceWrapper> invoiceList{get;set;}
    public Invoice__c invoice{get;set;}
    public String selectedStatus{get;set;}
    public String userDefaultCurrency{get;set;}
    public String userLanguage{get;set;}
     
    public TopPendingInvoicesCtrl() {
        userLanguage = UserInfo.getLanguage();
        if(userLanguage.trim() == 'fr'|| userLanguage.trim() == 'it'){
            userLanguage = '_'+userLanguage;
        }
        else{
            userLanguage = '';
        }
        invoice = new Invoice__c();
        userDefaultCurrency = UserInfo.getDefaultCurrency();
        selectedStatus = 'Both'; 
        User userLoggedIn = [Select Name,contactId, contact.AccountId FROM User WHERE id =: UserInfo.getUserId()];
        accId = userLoggedIn.Contact.AccountId;
        invoiceList = new List<InvoiceWrapper>();
        search();
    }
     
    // populate the top 5 invoices on the basis of due date and amount     
    public void search() {
        Set<String> stset = new Set<String>();
        invoiceList = new List<InvoiceWrapper>();
        if(selectedStatus == 'Both') {
            stset.add('Pending Approval (Open)');
            stset.add('Approved');
        }
        else {
            stset.add(selectedStatus);
        }
        System.debug('----------------> ' + stset);
        for(Invoice__c record: [SELECT id,Name, Custom_Currency__c, Due_Date__c, Amount__c,Input_Beneficiary__r.id,Input_Beneficiary__r.name, Status__c 
                        FROM Invoice__c 
       					WHERE Status__c In :stset
                        //AND Due_Date__c<=TODAY
                        AND Account__c =: accId
                         ORDER BY Due_Date_Span__c asc, Amount__c DESC
                        //ORDER BY Due_Date__c desc, Amount__c DESC 
                        LIMIT 5]){
            invoiceList.add(new InvoiceWrapper(record));                        
        }
        
    }
   
    public Boolean dataAvailable {
        get {  
            if(invoiceList.size() > 0) return true;
            else return false;
        }
    }
    
    public class InvoiceWrapper{
        public Invoice__c invoice{get;set;}
        public Decimal settlementCurrency{get;set;}
        public String settlementCurrencyFormat{get;set;}
        
        public InvoiceWrapper(Invoice__c invoice){
            this.invoice = invoice;
            settlementCurrency = Utility.getSettlementCurrencyAmount(invoice.Amount__c, invoice.Custom_Currency__c, UserInfo.getDefaultCurrency());
            settlementCurrencyFormat = settlementCurrency.format();
        }
    }
    
    
    
/*	public class InvoiceWpr implements Comparable{
   		public Invoice__c Invoice{get;set;}
   		public Integer diferenceDate{get;set;}
   		public Integer diferenceDateThis{get;set;}
   		public InvoiceWpr(Invoice__c InvoiceP){
   			Invoice = InvoiceP;
   		}
		public Integer compareTo(Object compareTo) {
            InvoiceWpr compareToEmp = (InvoiceWpr)compareTo;
            diferenceDate = System.today();
            if(compareToEmp.Due_Date__c>System.today()){
            	diferenceDate = compareToEmp.Due_Date__c -System.today(); 
            }else{
            	diferenceDate = System.today()- compareToEmp.Due_Date__c;
            }
            
            if (invYear > compareToEmp.invYear) return 1;
            if (invYear == compareToEmp.invYear)
            {
                if (invMonth == compareToEmp.invMonth) return 0;
                if (invMonth > compareToEmp.invMonth) return 1;
                return -1;
            }
            return -1;        
        }   		
   	}   */

}