objects/Input__c.object
<CustomObject>
    <fields>
        <fullName>Input_Beneficiary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer/Supplier</label>
        <referenceTo>Input_Beneficiary__c</referenceTo>
        <relationshipLabel>Inputs</relationshipLabel>
        <relationshipName>Inputs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Input_Type__c</fullName>
        <description>This is the selection list used on the page to create a new input record</description>
        <label>Input Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Inflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - WUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Outflow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Input_Beneficiary__c.object
<CustomObject>
    <fields>
        <fullName>Beneficiary_Email__c</fullName>
        <label>Buyer/Supplier Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Input_Beneficiary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beneficiary</label>
        <referenceTo>Input_Beneficiary__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/InputBeneficiaryDetailPageCntrl_Test.cls
// 
// (c) 2014 Appirio, Inc.
//
// InputBeneficiaryDetailPageCntrl_Test
// Test class for InputBeneficiaryDetailPageController
//
// 07 Apr, 2015    Ashish Goyal  Original (Ref. T-375697)
//
@isTest
private class InputBeneficiaryDetailPageCntrl_Test {
    
    static testMethod void testInputDetailController() {
        Input_Beneficiary__c inputBen = new Input_Beneficiary__c();
        inputBen.Name = 'Test Beneficiary';
        inputBen.Beneficiary_Email__c = 'Test@test12.com';
        insert inputBen;
        
        Input__c input = new Input__c();
        input.name =  'Testinput';
        input.Input_Type__c = 'Forecast Inflow';
        input.Input_Beneficiary__c = inputBen.Id;
        input.Window_Start_Date__c = Date.today();
        input.Window_End_Date__c = Date.today().addDays(5);
        insert input;
        
        Invoice__c invoice = new Invoice__c();
        invoice.name =  'TestInvoice';
        invoice.Input_Beneficiary__c = inputBen.Id;
        insert invoice;
        
        Test.startTest();
        PageReference pageRef = Page.InputBeneficiaryDetailPage;
        pageRef.getParameters().put('id', String.valueOf(inputBen.Id));
        Test.setCurrentPage(pageRef);
        InputBeneficiaryDetailPageController testCtrl = new InputBeneficiaryDetailPageController();
        System.assertNotEquals(testCtrl, null);
        testCtrl.customDelete();
        testCtrl.customCancel();
        testCtrl.doRedirect();
        Test.stopTest();
    }

}