objects/Input__c.object
<CustomObject>
    <fields>
        <fullName>Input_Type__c</fullName>
        <description>This is the selection list used on the page to create a new input record</description>
        <label>Input Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Inflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - WUBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Outflow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

classes/InputAutoFollowHandler_Test.cls
// 
// (c) 2014 Appirio, Inc.
//
// InputAutoFollowHandler_Test
// Test class for InputAutoFollowHandler
//
// 07 Apr, 2015    Ashish Goyal  Original (Ref. T-375827)
//
@isTest
private class InputAutoFollowHandler_Test {
	
	static Input__c input;
    
    static testMethod void testInputDetailController() {
		input = new Input__c();
        input.name =  'Testinput';
        input.Input_Type__c = 'Forecast Inflow';
        
        Test.startTest();
        insert input;
		System.assertNotEquals(input, null);
		Test.stopTest();
    }
}