objects/Input__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the transaction type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Inflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Outflow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NetCashFlowCtrl_test.cls
/**=====================================================================
 * Name: NetCashFlowCtrl_test
 * Description: Test class for NetCashFlowCtrl.cls
 * Created Date: Mar 16, 2015
 * Created By: Aashita Sharma 
 =====================================================================*/

@isTest
private class NetCashFlowCtrl_test {
    
    // creating test user
    private static User testUser; 
    
    // method  to cover NetCashFlowCtrl class
    static testMethod void testNetCashFlowCtrl() {
       
        createTestData();
        
        System.runAs(testUser){
            Test.startTest();
            NetCashFlowCtrl netController = new NetCashFlowCtrl();
            netController.Search();
            netController.getaccountTradedCurrency();
            NetCashFlowCtrl.loadAllTimeData();
           // to verify aggResult size should be 0
            System.assertEquals(NetCashFlowCtrl.aggResult.size(), 0);
            Test.stopTest();
        }
    }
     
     // creating test data for coverage
    public static void  createTestData(){ 
        testUser = test_Utility.createTestUser(true);
        System.runAs(testUser){
            Invoice__c invoice = test_Utility.createInvoice(true);
            Input__c input = test_Utility.createInput(false);
            input.Type__c = 'Forecast Inflow';
            input.Type__c = 'Purchase Order';
            insert input;
        }
    }
}