objects/Input__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the transaction type</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Orders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Inflow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflow - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Window Forward Contract - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Option - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forecast Outflow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Invoice Amount Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/NetCashFlowByCurrencyCtrlTest.cls
/**
 */
@isTest
private class NetCashFlowByCurrencyCtrlTest {
	
	static Account acc;
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        createTestData();
        ApexPages.currentPage().getParameters().put('aId',acc.Id);
        List<NetCashFlowCtrl.InvoicByCurrencyWrap> listwrpr = NetCashFlowByCurrencyCtrl.loadAllTimeData();
    }
    
    private static void createTestData(){
    	acc = new Account(name = 'acc');
    	insert acc;
    	List<Input__c> listInputs = new List<Input__c>();
    	Input__c input1 = new Input__c(Amount__c=20, Type__c='Forecast Inflow',Parent_Account__c=acc.Id);
    	listInputs.add(input1);
    	Input__c input2 = new Input__c(Amount__c=30, Type__c='Purchase Order',Parent_Account__c=acc.Id);
    	listInputs.add(input2);
    	Invoice__c invoice = new Invoice__c(Amount__c=30, Account__c=acc.Id);
    	insert invoice;
    	insert listInputs;
    }
}