objects/Input_Beneficiary__c.object
<CustomObject>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <formula>TEXT(CurrencyIsoCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Currency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Beneficiary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Beneficiary</label>
        <referenceTo>Input_Beneficiary__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Market_Rate__c.object
<CustomObject>
</CustomObject>

classes/ManageCashInputsCtlTest.cls
/**
 * Appirio, Inc
 * Name             : ManageCashInputsCtlTest
 * Created Date     : 30 April 2015 
 * Created By       : Nikhil Sharma (Appirio)
 * Description      : Test class for ManageCashInputsCtl
 */
@isTest
private class ManageCashInputsCtlTest {
	static Account acc;
    static testMethod void myUnitTest() {
       // System.currentPageReference().getParameters().put('sourcePage', 'InvoicesAndPayments');
        createTestData();
        ApexPages.currentPage().getParameters().put('aId', acc.Id);
        apexpages.currentPage().getParameters().put('cId','test12341234test');
        ManageCashInputsCtl ctrl = new ManageCashInputsCtl();
        ctrl.record.Input_Type__c ='Option - WUBS';
        ctrl.selectedCurrency = 'usd';
        ctrl.input.Window_Start_Date__c = Date.Today() ;
        ctrl.input.Window_End_Date__c = Date.Today().addDays(2);
        String str = ctrl.getTranslatedText();
        ctrl.NewRecord();
        ctrl.toggleIncomingSort();
        ctrl.togglehedgingSort();
        ctrl.toggleoutgoingSort();
        ctrl.PopulateLists();
        String contact = ctrl.findContact();
        ctrl.Cancel();
        ctrl.quickSave();
    }
    
    private static void createTestData() {
    	Market_Rate__c mktRate = new Market_Rate__c(Currency_Code__c = 'USD', Currency_Name__c='test', Currency_Value__c=5.0);
    	insert mktRate;
    	Input_Beneficiary__c inputBeneficiary = new Input_Beneficiary__c(Name = 'WUBS');
    	insert inputBeneficiary;    	
    	acc = new Account(name = 'acc');
    	insert acc;
    	Invoice__c invoice = new Invoice__c(account__c = acc.Id);
    	insert invoice;
    //	mktRate.Currency
    }
}