objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>AED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BWP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ParseAndDisplayCSVInvoice.cls
/**=====================================================================
 * Name: ParseAndDisplayCSVInvoice
 * Description: Related to ParseAndDisplayCSVInvoicePage Page
 * Created Date: Jan 13, 2015
 * Created By: Nishant Bansal (JDC)
 *
 * Date Modified  Feb 11,2015              Modified By   Vivek Ojha               Description of the update I-148135
 * Updates I-148135, By Vivek Ojha , Currency__c --> CurrencyIsoCode
 * Feb 12,2015							   Piyush Bansal						I-148263 : makiing all fields as required
 =====================================================================*/

public without sharing class ParseAndDisplayCSVInvoice extends ParseAndDisplayBaseCSVGenericCtl {
	public override String getsObjectName(){return 'invoice__c';} 
   	public ParseAndDisplayCSVInvoice(){
   		defaultSourcePage = 'InvoicesAndPayments';
   	}
   	public override list<GenericBaseCsvWrapper> parseCsv(String content){
   		parsedInput = new list<InvoiceCsvWrapper>();
   		return super.parseCsv(content);
   	}
   	public override void parseAttachment(Blob body, String name){
   		parsedInput = new list<InvoiceCsvWrapper>();
   		super.parseAttachment(body, name);
   	} 
   	public override GenericBaseCsvWrapper getGenericCsvWrapper(String[] tempFields, String transtype){
   		return new InvoiceCsvWrapper(tempFields, transtype);
   	}
   	public override void OnSaveUpdate(GenericBaseCsvWrapper inv) {
		inv.input.put('Account__c', Utility.currentAccount);
	}   	
}